# Generated by Django 3.2.16 on 2024-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='following_username',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
