# Generated by Django 3.2.16 on 2024-09-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240918_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_username',
            new_name='following',
        ),
    ]
