# Generated by Django 3.2.16 on 2024-09-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_following_username_follow_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='username',
        ),
    ]
